openapi: 3.0.3
info:
  title: Todo App - Tasks API
  description: Task CRUD endpoints for the Todo Full-Stack Web Application
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Local development server

security:
  - bearerAuth: []

paths:
  /tasks:
    get:
      summary: List all tasks
      description: Get all tasks belonging to the authenticated user
      operationId: listTasks
      tags:
        - Tasks
      responses:
        '200':
          description: List of user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskResponse'
              example:
                - id: 550e8400-e29b-41d4-a716-446655440001
                  title: Buy groceries
                  is_completed: false
                  created_at: '2026-01-11T10:00:00Z'
                  updated_at: '2026-01-11T10:00:00Z'
                - id: 550e8400-e29b-41d4-a716-446655440002
                  title: Call mom
                  is_completed: true
                  created_at: '2026-01-11T09:00:00Z'
                  updated_at: '2026-01-11T11:00:00Z'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: Not authenticated

    post:
      summary: Create task
      description: Create a new task for the authenticated user
      operationId: createTask
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
            example:
              title: Buy groceries
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              example:
                id: 550e8400-e29b-41d4-a716-446655440001
                title: Buy groceries
                is_completed: false
                created_at: '2026-01-11T10:00:00Z'
                updated_at: '2026-01-11T10:00:00Z'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: Title is required
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: Not authenticated

  /tasks/{task_id}:
    parameters:
      - name: task_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: Task unique identifier

    get:
      summary: Get task by ID
      description: Get a specific task belonging to the authenticated user
      operationId: getTask
      tags:
        - Tasks
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              example:
                id: 550e8400-e29b-41d4-a716-446655440001
                title: Buy groceries
                is_completed: false
                created_at: '2026-01-11T10:00:00Z'
                updated_at: '2026-01-11T10:00:00Z'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: Not authenticated
        '403':
          description: Forbidden - task belongs to another user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: Not authorized to access this task
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: Task not found

    put:
      summary: Update task
      description: Update the title of a task belonging to the authenticated user
      operationId: updateTask
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
            example:
              title: Buy groceries and vegetables
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              example:
                id: 550e8400-e29b-41d4-a716-446655440001
                title: Buy groceries and vegetables
                is_completed: false
                created_at: '2026-01-11T10:00:00Z'
                updated_at: '2026-01-11T12:00:00Z'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: Title cannot be empty
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: Not authenticated
        '403':
          description: Forbidden - task belongs to another user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: Not authorized to modify this task
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: Task not found

    delete:
      summary: Delete task
      description: Delete a task belonging to the authenticated user
      operationId: deleteTask
      tags:
        - Tasks
      responses:
        '200':
          description: Task deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              example:
                success: true
                message: Task deleted successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: Not authenticated
        '403':
          description: Forbidden - task belongs to another user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: Not authorized to delete this task
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: Task not found

  /tasks/{task_id}/toggle:
    parameters:
      - name: task_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: Task unique identifier

    patch:
      summary: Toggle task completion
      description: Toggle the completion status of a task belonging to the authenticated user
      operationId: toggleTask
      tags:
        - Tasks
      responses:
        '200':
          description: Task completion status toggled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
              example:
                id: 550e8400-e29b-41d4-a716-446655440001
                title: Buy groceries
                is_completed: true
                created_at: '2026-01-11T10:00:00Z'
                updated_at: '2026-01-11T12:00:00Z'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: Not authenticated
        '403':
          description: Forbidden - task belongs to another user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: Not authorized to modify this task
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: Task not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token in Authorization header

  schemas:
    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 500
          description: Task title (cannot be empty or whitespace only)

    UpdateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 500
          description: Updated task title (cannot be empty or whitespace only)

    TaskResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Task unique identifier
        title:
          type: string
          description: Task title
        is_completed:
          type: boolean
          description: Whether the task is completed
        created_at:
          type: string
          format: date-time
          description: Task creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Task last update timestamp

    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          description: Error message
